In [1]:
from __future__ import print_function,division
from builtins import range, input

In [2]:
from keras.models import Model
from keras.layers import Input, LSTM, GRU
import numpy as np
import matplotlib.pyplot as plt

Using TensorFlow backend.


In [6]:
T = 8  ## steps
D = 2  ## Dimesnion
M = 3  ## hidden layer size

In [7]:
X = np.random.randn(1,T,D)


#### Test output for 4 different RNN Structure

In [9]:
def lstm1():
    input_ = Input(shape = (T,D))
    rnn = LSTM(M,return_state = True)
    x = rnn(input_)
    
    model = Model(inputs = input_,outputs = x)
    o,h,c = model.predict(X)
    print("o:",o)
    print("h:",h)
    print("c:",c)
    
def lstm2():
    input_ = Input(shape = (T,D))
    rnn = LSTM(M,return_state = True,return_sequences = True)
    
    x = rnn(input_)
    
    model = Model(inputs = input_,outputs = x)
    o,h,c = model.predict(X)
    print("o:",o)
    print("h:",h)
    print("c:",c)
    
def gru1():
    input_ =Input(shape = (T,D))
    rnn = GRU(M,return_state = True)
    x = rnn(input_)
    
    model = Model(inputs = input_,outputs = x)
    o,h = model.predict(X)
    print("o:",o)
    print("h:",h)
    
def gru2():
    
    input_ = Input(shape = (T,D))
    rnn = GRU(M,return_state = True, return_sequences = True)
    x = rnn(input_)
    
    model = Model(inputs = input_,outputs = x)
    o,h = model.predict(X)
    print("o:",o)
    print("h:",h)
    
    
    
    

In [11]:
print("lstm1:")
lstm1()

print("lstm2:")
lstm2()
print("GRU1:")
gru1()
print("GRU2:")
gru2()

lstm1:
o: [[0.02030293 0.00614578 0.01596322]]
h: [[0.02030293 0.00614578 0.01596322]]
c: [[0.03973092 0.01195789 0.03236042]]
lstm2:
o: [[[ 0.11827926  0.10722892  0.04726928]
  [ 0.09318567  0.08347048  0.03399546]
  [ 0.18259788  0.07000379 -0.05464103]
  [-0.03666409 -0.03252876  0.02632205]
  [-0.08977496 -0.02005316  0.10993772]
  [-0.10601587 -0.18081094 -0.01313265]
  [-0.01158564 -0.07654999 -0.02647793]
  [-0.01751908 -0.01566291  0.04987927]]]
h: [[-0.01751908 -0.01566291  0.04987927]]
c: [[-0.03857115 -0.03132194  0.09630004]]
GRU1:
o: [[-0.07269662 -0.15312676 -0.01927128]]
h: [[-0.07269662 -0.15312676 -0.01927128]]
GRU2:
o: [[[-0.2121496   0.22251317  0.07165557]
  [-0.12156243  0.18900517  0.03984749]
  [-0.26389375  0.10816934  0.15760078]
  [ 0.05567673 -0.04096614 -0.2110617 ]
  [ 0.18427831  0.03409524 -0.2542231 ]
  [ 0.26170573 -0.46501485  0.01201261]
  [-0.00843237 -0.28285658  0.07129997]
  [-0.01433957 -0.05857997 -0.02500625]]]
h: [[-0.01433957 -0.05857997 -0.